---
title: "Project RMD"
author: "Group 2"
date: "11/30/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r}
library(MASS)
library(car)
#Load Data

setwd("d:/UTSA/Fall2020/DataMining/Project/stat-learning") # set working directory
df = read.csv('FinalDF.csv') # read in raw csv data


df$Age15_19 = as.factor(df$Age15_19)
df$Age20_24 = as.factor(df$Age20_24)
df$Age25_29 = as.factor(df$Age25_29)
df$Age30_34 = as.factor(df$Age30_34)
df$Age35_39 = as.factor(df$Age35_39)
df$Age40_44 = as.factor(df$Age40_44)
df$Age45_49 = as.factor(df$Age45_49)
df$Age50_54 = as.factor(df$Age50_54)
df$Age55_59 = as.factor(df$Age55_59)
df$Age60_64 = as.factor(df$Age60_64)

df$Australia = as.factor(df$Australia)
df$Belarus = as.factor(df$Belarus)
df$Belgium = as.factor(df$Belgium)
df$Canada = as.factor(df$Canada)
df$Denmark = as.factor(df$Denmark)
df$Finland = as.factor(df$Finland)
df$France = as.factor(df$France)
df$Germany = as.factor(df$Germany)
df$India = as.factor(df$India)
df$Ireland = as.factor(df$Ireland)
df$Japan = as.factor(df$Japan)
df$Mexico = as.factor(df$Mexico)
df$NZ = as.factor(df$NZ)
df$Russia = as.factor(df$Russia)
df$Singapore = as.factor(df$Singapore)
df$Spain = as.factor(df$Spain)
df$Sweden = as.factor(df$Sweden)
df$Switzerland = as.factor(df$Switzerland)
df$Ukraine = as.factor(df$Ukraine)
df$UK= as.factor(df$UK)
df$US= as.factor(df$US)

#update belarus temps
df$difference[163] = 10 
df$difference[177] = 10 
df$difference[224] = 10 
df$difference[255] = 10 
df$difference[266] = 10

exclude_vars <- names(df) %in% c("Runner" ,"Max", "Min", "Avg" ,"Age", "Team", "X" )
df.filtered <-df[,!exclude_vars]

#full model 
fit.lm = lm(Yards ~ .,data = df.filtered)
summary(fit.lm)

pairs(df[,grepl("avg_rate",names(df))])
pairs(df[,grepl("median_rate.",names(df))])
pairs(df[,grepl("rate_sd.",names(df))])

exclude_vars <- names(df) %in% c("Runner" ,"Max", "Min", "Avg" ,"Age", "Team", "Gen", "X", "Gender")
df.filtered <-df[,!exclude_vars]

plot(fit.lm)

```

```{r}
#Run Model w/ interaction effects
#0- age groups indicate 60-64 age group
#0 - countryies indicate Belarus

fit.lm.1 = lm(Yards ~ .+
                Finland:difference+
                Canada:difference+
                Ukraine:difference+
                Switzerland:difference+
                Denmark:difference+
                Belgium:difference+
                Ireland:difference+
                UK:difference+
                Germany:difference+
                France:difference+
                NZ:difference+
                US:difference+
                Japan:difference+
                Spain:difference+
                Australia:difference+
                Mexico:difference+
                India:difference+
                Singapore:difference+
                Russia:difference
                - rate_sd_diff_4_1
                -Age60_64                       
                -Sweden
                -Russia
                -Finland
                -Canada
                -Ukraine
                -Switzerland
                -Denmark
                -Belgium
                -Ireland
                -UK
                -Germany
                -France
                -NZ
                -US
                -Japan
                -Spain
                -Australia
                -Mexico
                -India
                -Singapore
                -Belarus
                - AvgSeconds #high vif
                ,data = df.filtered)

anova(fit.lm.1)

summary(fit.lm.1)

plot(fit.lm.1)

library(car)
vif(fit.lm.1)
```
```{r}
df.filtered$cubic_y = df.filtered$Yards^3
fit.lm.2 = lm(cubic_y ~ .+
                Finland:difference+
                Canada:difference+
                Ukraine:difference+
                Switzerland:difference+
                Denmark:difference+
                Belgium:difference+
                Ireland:difference+
                UK:difference+
                Germany:difference+
                France:difference+
                NZ:difference+
                US:difference+
                Japan:difference+
                Spain:difference+
                Australia:difference+
                Mexico:difference+
                India:difference+
                Singapore:difference+
                Russia:difference
                - rate_sd_diff_4_1
                -Age60_64                       
                -Sweden
                -Russia
                -Finland
                -Canada
                -Ukraine
                -Switzerland
                -Denmark
                -Belgium
                -Ireland
                -UK
                -Germany
                -France
                -NZ
                -US
                -Japan
                -Spain
                -Australia
                -Mexico
                -India
                -Singapore
                -Belarus
                - AvgSeconds #high vif
                ,data = df.filtered)

summary(fit.lm.2)

plot(fit.lm.2)

```
```{r}
boxplot(df$Yards)
mean(df$Yards)
median(df$Yards)
#remove points 1 and 2 almost 3x as large
df.filtered = df.filtered[-c(1),]
#df.filtered$cubic_y = df.filtered$Yards^(2)
fit.lm.2 = lm(Yards ~ .+
                Finland:difference+
                Canada:difference+
                Ukraine:difference+
                Switzerland:difference+
                Denmark:difference+
                Belgium:difference+
                Ireland:difference+
                UK:difference+
                Germany:difference+
                France:difference+
                NZ:difference+
                US:difference+
                Japan:difference+
                Spain:difference+
                Australia:difference+
                Mexico:difference+
                India:difference+
                Singapore:difference+
                Russia:difference
                - rate_sd_diff_4_1
                -Age60_64                       
                -Sweden
                -Russia
                -Finland
                -Canada
                -Ukraine
                -Switzerland
                -Denmark
                -Belgium
                -Ireland
                -UK
                -Germany
                -France
                -NZ
                -US
                -Japan
                -Spain
                -Australia
                -Mexico
                -India
                -Singapore
                -Belarus
                - AvgSeconds #high vif
                ,data = df.filtered)

summary(fit.lm.2)

plot(fit.lm.2)
a =boxCox(fit.lm.2,data = df.filtered)
?boxCox

library(olsrr)
ols_plot_resid_stud(fit.lm.2)
outlierTest(fit.lm.2, cutoff = .05)

```

```{r}

fit.lm.3 = lm(Yards ~ .+
                Finland:difference+
                Canada:difference+
                Ukraine:difference+
                Switzerland:difference+
                Denmark:difference+
                Belgium:difference+
                Ireland:difference+
                UK:difference+
                Germany:difference+
                France:difference+
                NZ:difference+
                US:difference+
                Japan:difference+
                Spain:difference+
                Australia:difference+
                Mexico:difference+
                India:difference+
                Singapore:difference+
                Russia:difference
                - rate_sd_diff_4_1
                - Age55_59
              - Age50_54
              - Age45_49
              - Age40_44
              - Age35_39
              - Age30_34
              - Age25_29
              - Age20_24
              - Age15_19
                -Age60_64                       
                -Sweden
                -Russia
                -Finland
                -Canada
                -Ukraine
                -Switzerland
                -Denmark
                -Belgium
                -Ireland
                -UK
                -Germany
                -France
                -NZ
                -US
                -Japan
                -Spain
                -Australia
                -Mexico
                -India
                -Singapore
                -Belarus
                - AvgSeconds #high vif
                ,data = df.filtered)
anova(fit.lm.2, fit.lm.3)

plot(Yards~AvgSeconds, data = df.filtered)

plot(Yards~MaxSeconds, data = df.filtered)
```
```{r}


fit.lm.4 = lm(Yards ~ .
                - rate_sd_diff_4_1
                -Age60_64                       
                -Sweden
                -Russia
                -Finland
                -Canada
                -Ukraine
                -Switzerland
                -Denmark
                -Belgium
                -Ireland
                -UK
                -Germany
                -France
                -NZ
                -US
                -Japan
                -Spain
                -Australia
                -Mexico
                -India
                -Singapore
                -Belarus
                - AvgSeconds #high vif
                ,data = df.filtered)
anova(fit.lm.4, fit.lm.2)

#Get rid of ages but keep interactions
```

```{r}


fit.lm.5 = lm(Yards ~ .+
                Finland:difference+
                Canada:difference+
                Ukraine:difference+
                Switzerland:difference+
                Denmark:difference+
                Belgium:difference+
                Ireland:difference+
                UK:difference+
                Germany:difference+
                France:difference+
                NZ:difference+
                US:difference+
                Japan:difference+
                Spain:difference+
                Australia:difference+
                Mexico:difference+
                India:difference+
                Singapore:difference+
                Russia:difference
- rate_sd_diff_4_1
- Age55_59
- Age50_54
- Age45_49
- Age40_44
- Age35_39
- Age30_34
- Age25_29
- Age20_24
- Age15_19
-Age60_64                       
-Sweden
-Russia
-Finland
-Canada
-Ukraine
-Switzerland
-Denmark
-Belgium
-Ireland
-UK
-Germany
-France
-NZ
-US
-Japan
-Spain
-Australia
-Mexico
-India
-Singapore
-Belarus
- AvgSeconds #high vif
                ,data = df.filtered)

plot(fit.lm.5)
summary(fit.lm.5)
vif(fit.lm.5)
```


```{r}

exclude_vars <- names(df.filtered) %in% c("rate_sd_diff_4_1",
"Age55_59",
"Age50_54",
"Age45_49",
"Age40_44",
"Age35_39",
"Age30_34",
"Age25_29",
"Age20_24",
"Age15_19",
"Age60_64",
"AvgSeconds"
)


df.filtered.2 <-df.filtered[,!exclude_vars]
```

```{r}

fit.lm.6 = lm(Yards ~ .+
                Finland:difference+
                Canada:difference+
                Ukraine:difference+
                Switzerland:difference+
                Denmark:difference+
                Belgium:difference+
                Ireland:difference+
                UK:difference+
                Germany:difference+
                France:difference+
                NZ:difference+
                US:difference+
                Japan:difference+
                Spain:difference+
                Australia:difference+
                Mexico:difference+
                India:difference+
                Singapore:difference+
                Russia:difference
                - difference                          
                -Sweden
                -Russia
                -Finland
                -Canada
                -Ukraine
                -Switzerland
                -Denmark
                -Belgium
                -Ireland
                -UK
                -Germany
                -France
                -NZ
                -US
                -Japan
                -Spain
                -Australia
                -Mexico
                -India
                -Singapore
                -Belarus
              ,data = df.filtered.2)
summary(fit.lm.6)
plot(fit.lm.6)

df.filtered.2$logy = log(df.filtered.2$Yards)

fit.lm.7 = lm(logy ~ .+
                Finland:difference+
                Canada:difference+
                Ukraine:difference+
                Switzerland:difference+
                Denmark:difference+
                Belgium:difference+
                Ireland:difference+
                UK:difference+
                Germany:difference+
                France:difference+
                NZ:difference+
                US:difference+
                Japan:difference+
                Spain:difference+
                Australia:difference+
                Mexico:difference+
                India:difference+
                Singapore:difference+
                Russia:difference
                - difference                          
                -Sweden
                -Russia
                - Yards
                -Finland
                -Canada
                -Ukraine
                -Switzerland
                -Denmark
                -Belgium
                -Ireland
                -UK
                -Germany
                -France
                -NZ
                -US
                -Japan
                -Spain
                -Australia
                -Mexico
                -India
                -Singapore
                -Belarus
              ,data = df.filtered.2)
summary(fit.lm.7)

df.filtered.2 = df.filtered.2[-c(94),]
df.filtered.2 = df.filtered.2[-c(124),]

plot(df.filtered.2$Yards ~range_q1+range_q2+range_q3+range_q4,data = df.filtered.2)


```
```{r}

fit.lm.8 = lm(logy ~ .+
                Finland:difference+
                Canada:difference+
                Ukraine:difference+
                Switzerland:difference+
                Denmark:difference+
                Belgium:difference+
                Ireland:difference+
                UK:difference+
                Germany:difference+
                France:difference+
                NZ:difference+
                US:difference+
                Japan:difference+
                Spain:difference+
                Australia:difference+
                Mexico:difference+
                India:difference+
                Singapore:difference+
                Russia:difference
                - difference                          
                -Sweden
                -Russia
                -Finland
                -Canada
                -Ukraine
                -Switzerland
                -Denmark
                -Belgium
                -Ireland
                -UK
                -Germany
                -France
                -NZ
                -US
                -Japan
                -Spain
                -Australia
                -Mexico
                - Yards
                -India
                -Singapore
                -Belarus
              ,data = df.filtered.2)
summary(fit.lm.8)
plot(fit.lm.8)
```


```{r}

fit.lm.9 = lm(logy ~ .+
                Finland:difference+
                Canada:difference+
                Ukraine:difference+
                Switzerland:difference+
                Denmark:difference+
                Belgium:difference+
                Ireland:difference+
                UK:difference+
                Germany:difference+
                France:difference+
                NZ:difference+
                US:difference+
                Japan:difference+
                Spain:difference+
                Australia:difference+
                Mexico:difference+
                India:difference+
                Singapore:difference+
                Russia:difference
                - difference
                - Yards
                -Sweden
                -Russia
                -Finland
                -Canada
                -Ukraine
                -Switzerland
                -Denmark
                -Belgium
                -Ireland
                -UK
                -Germany
                -France
                -NZ
                -US
                -Japan
                -Spain
                -Australia
                -Mexico
                -India
                -Singapore
                -Belarus
                - rate_sd1
                - rate_sd2
                -rate_sd3
                -rate_sd4
              ,data = df.filtered.2)
summary(fit.lm.9)
plot(fit.lm.9)

anova(fit.lm.9, fit.lm.8)
```

```{r}

fit.lm.10 = lm(logy ~ .+
                Finland:difference+
                Canada:difference+
                Ukraine:difference+
                Switzerland:difference+
                Denmark:difference+
                Belgium:difference+
                Ireland:difference+
                UK:difference+
                Germany:difference+
                France:difference+
                NZ:difference+
                US:difference+
                Japan:difference+
                Spain:difference+
                Australia:difference+
                Mexico:difference+
                India:difference+
                Singapore:difference+
                Russia:difference
                - difference
                - Yards
                -Sweden
              - median_rate_q1
              - median_rate_q2
              - median_rate_q3
              - median_rate_q4
                -Russia
                -Finland
                -Canada
                -Ukraine
                -Switzerland
                -Denmark
                -Belgium
                -Ireland
                -UK
                -Germany
                -France
                -NZ
                -US
                -Japan
                -Spain
                -Australia
                -Mexico
                -India
                -Singapore
                -Belarus
                - rate_sd1
                - rate_sd2
                -rate_sd3
                -rate_sd4
              ,data = df.filtered.2)
summary(fit.lm.10)
plot(fit.lm.10)

anova(fit.lm.9, fit.lm.10)
```

```{r}

fit.lm.11 = lm(logy ~ .+
                Finland:difference+
                Canada:difference+
                Ukraine:difference+
                Switzerland:difference+
                Denmark:difference+
                Belgium:difference+
                Ireland:difference+
                UK:difference+
                Germany:difference+
                France:difference+
                NZ:difference+
                US:difference+
                Japan:difference+
                Spain:difference+
                Australia:difference+
                Mexico:difference+
                India:difference+
                Singapore:difference+
                Russia:difference
                - difference
                - Yards
                -Sweden
              - median_rate_q1
              - median_rate_q2
              - median_rate_q3
              - median_rate_q4
              - median_sec_q2
              - median_sec_q3
              - median_sec_q4
                -Russia
                -Finland
                -Canada
                -Ukraine
                -Switzerland
                -Denmark
                -Belgium
                -Ireland
                -UK
                -Germany
                -France
                -NZ
                -US
                -Japan
                -Spain
                -Australia
                -Mexico
                -India
                -Singapore
                -Belarus
                - rate_sd1
                - rate_sd2
                -rate_sd3
                -rate_sd4
              ,data = df.filtered.2)
summary(fit.lm.11)
plot(fit.lm.11)

anova(fit.lm.11, fit.lm.10)
```
```{r}

fit.lm.12 = lm(logy ~ .+
                Finland:difference+
                Canada:difference+
                Ukraine:difference+
                Switzerland:difference+
                Denmark:difference+
                Belgium:difference+
                Ireland:difference+
                UK:difference+
                Germany:difference+
                France:difference+
                NZ:difference+
                US:difference+
                Japan:difference+
                Spain:difference+
                Australia:difference+
                Mexico:difference+
                India:difference+
                Singapore:difference+
                Russia:difference
                - difference
                - Yards
                -Sweden
              - median_rate_q1
              - median_rate_q2
              - median_rate_q3
              - median_rate_q4
              - median_sec_q2
              - median_sec_q3
              - median_sec_q4
              - avg_rate_q1
              - avg_rate_q2
              - avg_rate_q3
                -Russia
                -Finland
                -Canada
                -Ukraine
                -Switzerland
                -Denmark
                -Belgium
                -Ireland
                -UK
                -Germany
                -France
                -NZ
                -US
                -Japan
                -Spain
                -Australia
                -Mexico
                -India
                -Singapore
                -Belarus
                - rate_sd1
                - rate_sd2
                -rate_sd3
                -rate_sd4
              ,data = df.filtered.2)
summary(fit.lm.12)
plot(fit.lm.12)

anova(fit.lm.11, fit.lm.12)
```
```{r}
fit.lm.13 = lm(logy ~ .+
                Finland:difference+
                Canada:difference+
                Ukraine:difference+
                Switzerland:difference+
                Denmark:difference+
                Belgium:difference+
                Ireland:difference+
                UK:difference+
                Germany:difference+
                France:difference+
                NZ:difference+
                US:difference+
                Japan:difference+
                Spain:difference+
                Australia:difference+
                Mexico:difference+
                India:difference+
                Singapore:difference+
                Russia:difference
                - difference
                - Yards
                -Sweden
              - median_rate_q1
              - median_rate_q2
              - median_rate_q3
              - median_rate_q4
              - median_sec_q2
              - median_sec_q3
              - median_sec_q4
              - avg_rate_q1
              - avg_rate_q2
              - avg_rate_q3
                -Russia
              - MaxSeconds
                -Finland
                -Canada
                -Ukraine
                -Switzerland
                -Denmark
                -Belgium
                -Ireland
                -UK
                -Germany
                -France
                -NZ
                -US
                -Japan
                -Spain
                -Australia
                -Mexico
                -India
                -Singapore
                -Belarus
                - rate_sd1
                - rate_sd2
                -rate_sd3
                -rate_sd4
              ,data = df.filtered.2)
summary(fit.lm.13)
plot(fit.lm.13)
anova(fit.lm.13, fit.lm.12)
```
```{r}
fit.lm.14 = lm(logy ~ .+
                Finland:difference+
                Canada:difference+
                Ukraine:difference+
                Switzerland:difference+
                Denmark:difference+
                Belgium:difference+
                Ireland:difference+
                UK:difference+
                Germany:difference+
                France:difference+
                NZ:difference+
                US:difference+
                Japan:difference+
                Spain:difference+
                Australia:difference+
                Mexico:difference+
                India:difference+
                Singapore:difference+
                Russia:difference
                - difference
                - Yards
                -Sweden
              - median_rate_q1
              - median_rate_q2
              - median_rate_q3
              - median_rate_q4
              - median_sec_q2
              - median_sec_q3
              - median_sec_q4
              - avg_rate_q1
              - avg_rate_q2
              - avg_rate_q3
                -Russia
              - MaxSeconds
                -Finland
                -Canada
                -Ukraine
                -Switzerland
                -Denmark
                -Belgium
                -Ireland
                -UK
                -Germany
                -France
                -NZ
                -US
                -Japan
                -Spain
                -Australia
                -Mexico
                -India
                -Singapore
                -Belarus
                - rate_sd1
                - rate_sd2
                -rate_sd3
                -rate_sd4
                -avg_sec_q2
                -sd_q2
                - avg_sec_q4
              ,data = df.filtered.2)
summary(fit.lm.14)
plot(fit.lm.14)
anova(fit.lm.14, fit.lm.13)
```
```{r}
fit.lm.15 = lm(logy ~ .
                - Yards
                -Sweden
              - median_rate_q1
              - median_rate_q2
              - median_rate_q3
              - median_rate_q4
              - median_sec_q1
             - median_sec_q2
              - median_sec_q3
              - median_sec_q4
              - avg_rate_q1
              - avg_rate_q2
              - avg_rate_q3
                -Russia
              - MaxSeconds
                -Finland
                -Canada
                -Ukraine
                -Switzerland
                -Denmark
                -Belgium
                -Ireland
                -UK
                -Germany
                -France
                -NZ
                -US
                -Japan
                -Spain
                -Australia
                -Mexico
                -India
                -Singapore
                -Belarus
                - rate_sd1
                - rate_sd2
                -rate_sd3
                -rate_sd4
                -avg_sec_q2
               -avg_sec_q1
                -sd_q2
                - avg_sec_q4
              - range_q2
              ,data = df.filtered.2)
summary(fit.lm.15)
plot(fit.lm.15)
anova(fit.lm.14, fit.lm.15)
```
```{r}
fit.glm = glm(logy ~ .
                - Yards
                -Sweden
              - median_rate_q1
              - median_rate_q2
              - median_rate_q3
              - median_rate_q4
              - median_sec_q1
             - median_sec_q2
              - median_sec_q3
              - median_sec_q4
              - avg_rate_q1
              - avg_rate_q2
              - avg_rate_q3
                -Russia
              - MaxSeconds
                -Finland
                -Canada
                -Ukraine
                -Switzerland
                -Denmark
                -Belgium
                -Ireland
                -UK
                -Germany
                -France
                -NZ
                -US
                -Japan
                -Spain
                -Australia
                -Mexico
                -India
                -Singapore
                -Belarus
                - rate_sd1
                - rate_sd2
                -rate_sd3
                -rate_sd4
                -avg_sec_q2
               -avg_sec_q1

                -sd_q2
                - avg_sec_q4
              - range_q2
              ,data = df.filtered.2)
summary(fit.glm)
anova(fit.glm)
plot(fit.glm)
vif(fit.glm)
library(boot)
cv.err = cv.glm(df.filtered.2, fit.glm)
cv.err$delta

for (j in 1:10) {
  error <- c()
  for (i in 1:nrow(df.filtered.2)) {
    model <- glm(logy ~ .
                - Yards
                -Sweden
              - median_rate_q1
              - median_rate_q2
              - median_rate_q3
              - median_rate_q4
              - median_sec_q1
             - median_sec_q2
              - median_sec_q3
              - median_sec_q4
              - avg_rate_q1
              - avg_rate_q2
              - avg_rate_q3
                -Russia
              - MaxSeconds
                -Finland
                -Canada
                -Ukraine
                -Switzerland
                -Denmark
                -Belgium
                -Ireland
                -UK
                -Germany
                -France
                -NZ
                -US
                -Japan
                -Spain
                -Australia
                -Mexico
                -India
                -Singapore
                -Belarus
                - rate_sd1
                - rate_sd2
                -rate_sd3
                -rate_sd4
                -avg_sec_q2
                -avg_sec_q1
                -sd_q2
                - avg_sec_q4
              - range_q2, data = df.filtered.2[-i,])
    prediction <- predict(model, newdata = df.filtered.2[i,])
    error[i] <- (prediction - df.filtered.2[i, "logy"]) ^ 2
    if (i == nrow(df.filtered.2)) {
      LOOCV_MSE <- mean(error)
    }
  }
}
LOOCV_MSE








```
